//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAB_SPECIFICNA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LAB_SPECIFICNA()
        {
            this.RASPOREDs = new HashSet<RASPORED>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> vremeOd { get; set; }
        public Nullable<System.DateTime> vremeDo { get; set; }
        public Nullable<int> redosled { get; set; }
        public Nullable<int> Id_Lab_vezbe { get; set; }
    
        public virtual LAB_VEZBA LAB_VEZBA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RASPORED> RASPOREDs { get; set; }
    }
}
