//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class RASPORED
    {
        public int id { get; set; }
        public Nullable<int> student { get; set; }
        public Nullable<int> lab_vezba { get; set; }
        public Nullable<System.DateTime> pocetak_laba { get; set; }
        public Nullable<System.DateTime> zavrsetak_laba { get; set; }
    
        public virtual LAB_SPECIFICNA LAB_SPECIFICNA { get; set; }
        public virtual STUDENT STUDENT1 { get; set; }
    }
}
